language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - CI=TRAVISCI
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run report-coverage
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs
  on:
    branch: master
  name: Cristian Boarna